### ISSUE TITLE
Laravel include notifications

### ISSUE THREAD

**Issue by Artessan** [christophrumpel/nova-notifications#12]
Hi Christoph! First thanks for this package! Second the default Laravel notification like Password reset and verify email are not loaded I check others issues and the code base and saw that you autoload the notification for App namespace. Can you think on the posibility of add custom namespace for the search? In that way is posible semi-autoload notifications from other packages

**Comment by christophrumpel** [comment]
Hey, thanks a lot. Ah right, good point.

So I could add a config file to that people can add custom namespaces. Or I could just check all classes hmm... What do you think?

**Comment by Artessan** [comment]
A config file is the best option I think, in that way the namespace can be added and maybe in the config can be a option for exclude notifications (I dont know if this has some real utility but can be an option) 

And again Thanks a lot!!!

**Comment by christophrumpel** [comment]
Hey, I just published a new release with the ability to publish a config file. (see readme)
Can you test it?

**Comment by Artessan** [comment]
Hey, Tested, Thank you so much, is working perfectly.

**Comment by christophrumpel** [comment]
Ok great to hear that 👍 I'm still struggling with how to handle all the different parameters that a notification can have. Sending them often does not work. But yeah, it is still an experiment =)
