### ISSUE TITLE
[Request] Translations and authorizations

### ISSUE THREAD

**Issue by MarceauKa** [christophrumpel/nova-notifications#2]
Please make it possible to translate Vue components and the `navigation` view.

**Comment by christophrumpel** [comment]
Hey, good idea. Need to take a look at how to best approach this. Any recommendations?

Can I also ask if you're already using this package and what's your opinion on it? Still trying to think about how develop new features.

**Comment by MarceauKa** [comment]
Hi! Thank you for your answer.

For translation, you certainly want to use the "__('My text')" helper. Example in Nova components: `{{__('Previous')}}`.

Just installed it. For now, I've a bug with the Send functionnality. The component retrieve my notifications classes (seen in the network tab), but raise an error.

<img width="891" alt="capture d ecran 2018-09-18 a 18 02 41" src="https://user-images.githubusercontent.com/1665333/45700525-14d2f880-bb6d-11e8-9e68-9e1284bb562c.png">

**Comment by christophrumpel** [comment]
Hey, ok thanks. You can also do a PR for translation if you like =) If not I will look at it the next days.

Regarding the bug: Do you get the error when you click the `send` button or before?

Authorization methods would be a nice addition as well, thanks 👍

**Comment by MarceauKa** [comment]
Hi, look at my PR #3  :)
