### ISSUE TITLE
Send page error

### ISSUE THREAD

**Issue by talismandev** [christophrumpel/nova-notifications#32]
Hello! 

I am encountering strange error on Send Page: 
http://prntscr.com/16b5z20

And the page is empty.

PHP Version: 7.4.19
Laravel Framework Version:  8.45.1
Nova version: 3.26.1

**Comment by christophrumpel** [comment]
Hey, this repo isn't maintained anymore. I'd recommend not to use it unless you are just want to try it out. Regarding the error, I can't tell out of my head what it is about.

**Comment by talismandev** [comment]
Okay.

Anyway, thanks for the answer. 
I will close the issue.
