### ISSUE TITLE
Unexpected global styles changes.

### ISSUE THREAD

**Issue by slavarazum** [christophrumpel/nova-notifications#9]
Looks like tool styles overrides default Nova styles.

![Tool Styles](https://image.prntscr.com/image/-Tj5bHN_S7yNd23WkjLXKA.png)

It breaks main Nova template. Possible the problem hiding in **app.css** file

```css
@tailwind components;
@tailwind utilities;
```

**Comment by christophrumpel** [comment]
Hey @slavarazum . Are you using the latest version?

**Comment by slavarazum** [comment]
@christophrumpel Yep, just installed 1.0.5

**Comment by christophrumpel** [comment]
Ok then I will check it. Which element are you checking in the screenshot?

**Comment by slavarazum** [comment]
Try to check any sidebar label:
![Inspection](https://image.prntscr.com/image/-esD0X6MQfyLcG6NHHgV0g.png)

With disabled notifications tool:
![Inspection](https://image.prntscr.com/image/JuHuIJchQUerhzGAlWrzZA.png)

**Comment by XGhozt** [comment]
Came here to post this. They're in the `/dist/css/tool.css` file. 
Need this removed before I can use the package. 😞

**Comment by christophrumpel** [comment]
The problem is that Nova comes with a very limited set of TailwindCSS styles. I will take a look at it today. Thanks for the info guys 👍

**Comment by christophrumpel** [comment]
I just published a new release 1.0.6 where I removed the custom styles. I will think of a better way to include them later. Please let me know if everything is working now.

**Comment by slavarazum** [comment]
@christophrumpel Yep, thanks, now it works fine!

**Comment by christophrumpel** [comment]
perfect 👍
